name: Train RankNet

on:

  push:
    paths:
      - "train.py"
      - "*.json"

  workflow_dispatch:

jobs:

  train:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install numpy
          pip install tensorflow==2.16.1
          pip install tensorflowjs==4.17.0

      - name: Train model
        run: python train.py

      - name: Show output files
        run: |
          echo "=== OUTPUT FILES ==="
          find output

      - name: Upload artifacts
        uses: actions/upload-artifact@v4

        with:
          name: ranknet-models

          path: |
            output/ranknet.keras
            output/tfjs_model

          retention-days: 90
