name: Train and Export Model

# Run on push to main branch or manually from the Actions tab
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Installing tensorflow and tensorflowjs
          pip install tensorflow tensorflowjs numpy

      - name: Run training script
        run: |
          python train.py

      - name: Upload TFJS Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: browser-ready-model
          path: output/tfjs_model/
          retention-days: 14 # Keeps the file available to download for 14 days
